// Auto-generated by the postman-to-k6 converter

import "./libs/shim/core.js";
import "./libs/shim/expect.js";
import { htmlReport } from "https://raw.githubusercontent.com/benc-uk/k6-reporter/main/dist/bundle.js";

export let options = { maxRedirects: 4 ,
  vus: 10,
  duration: '30s',

};

const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  options
});

export default function() {
  postman[Request]({
    name: "New Request",
    id: "8dfc46da-66aa-4a51-b411-5c710667fd4c",
    method: "GET",
    address: "https://reqres.in/api/users?page=2",
    post(response) {
      // Status Code  Assertion
      pm.test("Status code is 200", function() {
        pm.response.to.have.status(200);
      });

      // Response Body Assertion (Contains String)
      pm.test("Body must contain the string", function() {
        pm.expect(pm.response.text()).to.include("first_name");
      });

      // Response Body Assertion (JSON value Check)
      pm.test("JSON Value check", function() {
        var jsonData = pm.response.json();
        pm.expect(jsonData.value).to.eql(undefined);
      });

      // Response Time Assertion
      pm.test("Response time is less than 500ms", function() {
        pm.expect(pm.response.responseTime).to.be.below(5000);
      });
    }
  });
}

export function handleSummary(data) {
  return {
    "summary.html": htmlReport(data),
  };
}

